### ISSUE TITLE
RSS link is wrong

### ISSUE THREAD

**Issue by iglpdc** [cavaunpeu/willwolf.io-source#26]
Hi @cavaunpeu, I wanted to subscribe to your RSS feed and got a 404 page. It seems the link added by pelican sends you to `feeds/all.atom.xml`, but *relative* to the page you're currently in. 

I think you're missing a ``{{ main_url }}`` before `{{ FEED_ATOM }}` in the line below.

https://github.com/cavaunpeu/willwolf.io-source/blob/820036f4b37879c12d6cbd03dff8d2911d397a8d/theme/templates/head.html#L17

(Very nice blog, BTW :smile: )

**Comment by williamabrwolf** [comment]
Fixed, I think! Thanks so much!
